/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Ivan David
 */
public class ViewMVCMayor extends javax.swing.JPanel {

    /**
     * Creates new form ViewMVCMayor
     */
    public ViewMVCMayor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_contenedor2 = new javax.swing.JPanel();
        jl_instrucciones = new javax.swing.JLabel();
        jl_numero1 = new javax.swing.JLabel();
        jl_numero2 = new javax.swing.JLabel();
        jl_numero3 = new javax.swing.JLabel();
        jtf_numero1 = new javax.swing.JTextField();
        jtf_numero3 = new javax.swing.JTextField();
        jtf_numero2 = new javax.swing.JTextField();
        jtbn_calcular = new javax.swing.JButton();
        jp_encabezado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jp_contenedor2.setBackground(new java.awt.Color(133, 121, 255));

        jl_instrucciones.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_instrucciones.setText("Introduce los siguientes valores:");

        jl_numero1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_numero1.setText("Numero 1:");

        jl_numero2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_numero2.setText("Numero 2:");

        jl_numero3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jl_numero3.setText("Numero 3:");

        jtbn_calcular.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jtbn_calcular.setText("Calcular");

        javax.swing.GroupLayout jp_contenedor2Layout = new javax.swing.GroupLayout(jp_contenedor2);
        jp_contenedor2.setLayout(jp_contenedor2Layout);
        jp_contenedor2Layout.setHorizontalGroup(
            jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedor2Layout.createSequentialGroup()
                .addGroup(jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jp_contenedor2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jp_contenedor2Layout.createSequentialGroup()
                                .addComponent(jl_numero2)
                                .addGap(35, 35, 35)
                                .addComponent(jtf_numero2))
                            .addGroup(jp_contenedor2Layout.createSequentialGroup()
                                .addComponent(jl_numero3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtf_numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jp_contenedor2Layout.createSequentialGroup()
                                .addComponent(jl_numero1)
                                .addGap(35, 35, 35)
                                .addComponent(jtf_numero1))
                            .addComponent(jl_instrucciones)))
                    .addGroup(jp_contenedor2Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jtbn_calcular)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jp_contenedor2Layout.setVerticalGroup(
            jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_contenedor2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jl_instrucciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero1)
                    .addComponent(jtf_numero1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_numero2)
                    .addComponent(jtf_numero2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jp_contenedor2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_numero3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_numero3))
                .addGap(18, 18, 18)
                .addComponent(jtbn_calcular)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jp_encabezado.setBackground(new java.awt.Color(0, 0, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Cual es el numero mayor?");

        javax.swing.GroupLayout jp_encabezadoLayout = new javax.swing.GroupLayout(jp_encabezado);
        jp_encabezado.setLayout(jp_encabezadoLayout);
        jp_encabezadoLayout.setHorizontalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_encabezadoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jp_encabezadoLayout.setVerticalGroup(
            jp_encabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jp_encabezadoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jp_contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jp_encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jp_encabezado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jp_contenedor2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jl_instrucciones;
    private javax.swing.JLabel jl_numero1;
    private javax.swing.JLabel jl_numero2;
    private javax.swing.JLabel jl_numero3;
    private javax.swing.JPanel jp_contenedor2;
    private javax.swing.JPanel jp_encabezado;
    public javax.swing.JButton jtbn_calcular;
    public javax.swing.JTextField jtf_numero1;
    public javax.swing.JTextField jtf_numero2;
    public javax.swing.JTextField jtf_numero3;
    // End of variables declaration//GEN-END:variables
}
