/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Ivan David
 */
public class ViewOperaciones extends javax.swing.JPanel {

    /**
     * Creates new form ViewOperaciones
     */
    public ViewOperaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_num = new javax.swing.JLabel();
        jl_num2 = new javax.swing.JLabel();
        jtf_num1 = new javax.swing.JTextField();
        jl_res = new javax.swing.JLabel();
        jtf_res = new javax.swing.JTextField();
        jbtn_resta = new javax.swing.JButton();
        jtbn_suma = new javax.swing.JButton();
        jtbn_multiplicacion = new javax.swing.JButton();
        jtbn_division = new javax.swing.JButton();
        jtf_num2 = new javax.swing.JTextField();

        jl_num.setText("Numero1:");

        jl_num2.setText("Numero2:");

        jl_res.setText("Resultado:");

        jbtn_resta.setText("-");

        jtbn_suma.setText("+");

        jtbn_multiplicacion.setText("*");

        jtbn_division.setText("/");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jl_res)
                            .addComponent(jl_num2)
                            .addComponent(jl_num))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_num2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_num1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtf_res, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jbtn_resta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtbn_suma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtbn_multiplicacion)
                        .addGap(18, 18, 18)
                        .addComponent(jtbn_division)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_num)
                    .addComponent(jtf_num1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jl_num2)
                    .addComponent(jtf_num2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_res)
                    .addComponent(jtf_res, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtn_resta)
                    .addComponent(jtbn_division)
                    .addComponent(jtbn_multiplicacion)
                    .addComponent(jtbn_suma))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jbtn_resta;
    public javax.swing.JLabel jl_num;
    public javax.swing.JLabel jl_num2;
    public javax.swing.JLabel jl_res;
    public javax.swing.JButton jtbn_division;
    public javax.swing.JButton jtbn_multiplicacion;
    public javax.swing.JButton jtbn_suma;
    public javax.swing.JTextField jtf_num1;
    public javax.swing.JTextField jtf_num2;
    public javax.swing.JTextField jtf_res;
    // End of variables declaration//GEN-END:variables

    
}
